name: Docker Image CI

on:
  push:
    paths:
      - 'app/**'

jobs:
  BuildImage:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: rusty-actions/dockerfile-linter@v1
        with:
          dockerfile: app/Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: 'arm64,arm'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_INFI }}
          password: ${{ secrets.DOCKERHUB_TOKEN_INFI }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64 #,linux/amd64
          context: "app"  # Replace {{defaultContext}} with the actual context
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME_INFI }}/webapp:latest #-${{ github.sha }}

  DeployImage:
    needs: BuildImage
    runs-on: self-hosted
    steps:
      - name: Trigger App Deployment from Ansible repo
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: bithost
          repo: school_ansible
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          github_user: bithost
          workflow_file_name: ansible-manual-deploy.yml
          ref: main
          wait_interval: 10
          client_payload: '{}'
          propagate_failure: false
          trigger_workflow: true
          wait_workflow: true
