name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    env:
      POCKETBASE_URL: ${{ vars.POCKETBASE_URL }}
      POCKETBASE_ADMIN_EMAIL: ${{ vars.POCKETBASE_ADMIN_EMAIL }}
      POCKETBASE_ADMIN_PASSWORD: ${{ secrets.POCKETBASE_ADMIN_PASSWORD }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Create config.py
      run: |
        cd app
        echo "POCKETBASE_URL = '${{ vars.POCKETBASE_URL }}'" > config.py
        echo "POCKETBASE_ADMIN_EMAIL = '${{ vars.POCKETBASE_ADMIN_EMAIL }}'" >> config.py
        echo "POCKETBASE_ADMIN_PASSWORD = '${{ secrets.POCKETBASE_ADMIN_PASSWORD }}'" >> config.py
        
    - name: Install dependencies
      run: |
        cd app
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        cd app
        python -m pytest
